blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
)
from . import views

app_name="blog"

urlpatterns = [
    path('', PostListView.as_view(), name='blog-base'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from homepage import views as user_views
from blog.views import PostDetailView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'

urlpatterns = [
    path('',views.index,name='index'),
    path('seperate/<str:subject>/',views.seperate,name='seperate'),
    path('search/',views.search,name='search'),
    path('year/<str:year>/',views.more,name='more'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.log_in,name='log_in'),
    path('logout/',views.log_out,name='log_out'),
    path('year/',views.year,name='year'),
    path('FirstYear/',views.fy,name='fy'),
    path('ITbranch/',views.it,name='it'),
    path('Mechbranch/',views.mech,name='mech'),
    path('Compbranch/',views.comp,name='comp'),
    path('Extcbranch/',views.extc,name='extc'),
    path('Instrubranch/',views.instru,name='instru'),
    path('Civilbranch/',views.civil,name='civil'),
    path('<str:title>/',views.detail,name='bk_detail'),
]

homepage/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image

class Category(models.Model):
    year = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    
    def __str__(self):
        return self.year


class Subject(models.Model):
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_logo = models.FileField()
    sub_title = models.CharField(max_length=100)
      
    
    def __str__(self):
        return self.sub_title

class Book(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    author= models.CharField(max_length=100)
    book_logo= models.FileField()
    book_title= models.CharField(max_length=200)
    book_detail=models.CharField(max_length=1000)
    book= models.FileField(blank= True,null=True,upload_to="static/homepage/")
      
    def __str__(self):
        return self.book_title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    image= models.FileField()

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

homepage/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from .forms import UserUpdateForm, ProfileUpdateForm
from django.db.models import Q
from .models import Subject,Category,Book
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required


#from django.http import HttpResponse
#from django.template import loader

def index(request):
    return render(request,'homepage/index.html')

        
def seperate(request,subject):
    title=str(subject)
    subject=Subject.objects.get(sub_title__startswith=title)
    return render(request,'homepage/seperate.html',{'subject':subject})
    #return HttpResponse("<h1>Book name:</h2>")


def search(request):
    query=request.GET.get('q')

    if query:
        category=Category.objects.filter(Q(year__icontains=query) | Q(branch__icontains=query))
        subject=Subject.objects.filter(Q(sub_title__icontains=query))
        book=Book.objects.filter(Q(book_title__icontains=query) | Q(author__icontains=query))
    return render(request,"homepage/search.html",{'category':category,'subject':subject,'book':book})

def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                category=Category.objects.all()
                return render(request,'homepage/year.html',{'category':category})
    return render(request, 'homepage/signup.html', {"form": form})

def log_in(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    category=Category.objects.all()
                    return render(request,'homepage/year.html',{'category':category})
            else:
                return render(request, 'homepage/log_in.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'homepage/log_in.html', {'error_message': 'Invalid login'})
    return render(request, 'homepage/log_in.html')

def log_out(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'homepage/log_in.html', context)

def year(request):
    """if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:"""
    category=Category.objects.all()
    return render(request,'homepage/year.html',{'category':category})

def fy(request):
    category=Category.objects.filter(branch="Fy")
    return render(request,'homepage/year.html',{'category':category})


def it(request):
    category=Category.objects.filter(branch="Information Technology")
    return render(request,'homepage/year.html',{'category':category})


def mech(request):
    category=Category.objects.filter(branch="Mechanical")
    return render(request,'homepage/year.html',{'category':category})


def comp(request):
    category=Category.objects.filter(branch="Computer Technology")
    return render(request,'homepage/year.html',{'category':category})


def extc(request):
    category=Category.objects.filter(branch="Electronics and Telecommunication")
    return render(request,'homepage/year.html',{'category':category})


def instru(request):
    category=Category.objects.filter(branch="Instrumentation")
    return render(request,'homepage/year.html',{'category':category})


def civil(request):
    category=Category.objects.filter(branch="Civil")
    return render(request,'homepage/year.html',{'category':category})



def more(request,year):
    year=str(year)
    category=Category.objects.get(year__startswith=year)
    subject=Subject.objects.all()
    return render(request,'homepage/more.html',{'category':category,'subject':subject})

def detail(request,title):
    #return HttpResponse("<h1>Book name: "+str(title)+"</h2>")
    title=str(title)
    book=Book.objects.get(book_title__startswith=title)
    return render(request,'homepage/bk_detail.html',{'bk':book})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'homepage/profile.html', context)

homepage/templates/homepage/bk_detail.html
{% extends 'homepage/navigate.html' %}
{% block title %}Books{% endblock %}

{% block body %}
<div class="row" id="section">
    <div><br/>
    <p id="ebk">{{ bk.book_title }}</p>
    </div>&nbsp;
    <div class="container-fluid">
        <img src="{{ bk.book_logo.url }}" class="img-responsive" id="bk_cover"/>
        <div class="caption" id="pic">
            <div >
                <p id="detail">{{ bk.author }}</p>&nbsp;<p id="detail">{{ bk.book_detail }}</p>
                {% if user.is_authenticated %}
                <a href="{{ bk.book.url }}" class="btn btn-info btn-lg" id="download">
                    <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                {% else %}
                <a href="#" class="btn btn-info btn-lg" id="launcher">
                        <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                {% endif %}
            </div>
        </div>                   
    </div>&nbsp;
    </div>
{% endblock %}

homepage/templates/homepage/index.html
{% extends 'homepage/navigate.html' %}

{% block body %}
&nbsp;
<div class="container-fluid">
      <div class="row">
        <div class="carousel slide" id="carousel-example" data-ride="carousel">
    
          <ol class="carousel-indicators">
            <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example" data-slide-to="1"></li>
            <li data-target="#carousel-example" data-slide-to="2"></li>
          </ol>
            <div class="carousel-inner">
                <div class="item active"><a href="#"><img src="/media/static/im1.jpg"></a>
                  <div class="carousel-caption">
                    <h3 id="intro" >Ebook</h3>
                      <p id="index" >a collection of engineering reference books to download for free</p>
                  </div>
                </div>

                <div class="item"><a href="#"><img style="width: 100%" src="/media/static/im2.jpg">
                  <div class="carousel-caption"><p id="index" style="color:gray" >You  can find any book by searching the book's name or author's name</p></div></a>
                </div>

                <div class="item"><a href="#"><img style="width: 100%" src="/media/static/im3.jpg"></a></div>
            </div>
    
    
            <a class="left carousel-control" data-slide="prev" href="#carousel-example"><span class="sr-only">Previous</span></a> 
            <a class="right carousel-control" data-slide="next" href="#carousel-example"> <span class="sr-only">Next</span></a>
        </div>
    </div>
    </div>

{% endblock %}

homepage/templates/homepage/log_in.html
{% extends 'homepage/navigate.html' %}
{% block title %}Login{% endblock %}

{% block body %}

<form action="{% url 'homepage:log_in' %}" method="POST">
    {% csrf_token %}
    <div id="login-box">
        <div class="left">
            <h1 id="h1">Log in</h1>
                {% if error_message %}
                <p style="color:white"><strong>{{ error_message }}</strong></p>
                {% endif %}
                <input type="text" name="username" placeholder="Username" />
                <input type="password" name="password" placeholder="Password" />            
                {% if request.GET.next %} 
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <input type="submit" name="login_submit" value="Login" />&nbsp;
        </div>
        <span id="p">Don't have an account<a href="{% url 'homepage:signup' %}">&nbsp;Signup</a></span>
    </div>
</form>
{% endblock %}

homepage/templates/homepage/more.html
{% extends 'homepage/navigate.html' %}
{% block title %}Subject{% endblock %}

{% block body %}
    <div class="row" id="section">
        <div>
        <p id="title" class="well">Books ({{category.year}})</p>
        </div>
        <div class="container-fluid">
            {% for subject in category.subject_set.all %}
                <div class="col-sm-12">
                <hr/>
                <p id="title1" style="font-size: 40px;">{{subject.sub_title}}</p>
                </div>
                {% for bk in subject.book_set.all %}
                    <div class="col-sm-4 col-lg-2" > &nbsp;
                                <a href="{% url 'homepage:bk_detail' bk.book_title %}"><img src="{{ bk.book_logo.url }}" class="img-responsive" id="covers">
                            <div class="caption" id="pic">
                                <p>{{ bk.book_title }}</p></a><p>{{ bk.author }}</p>&nbsp;
                            </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>  
{% endblock %}

homepage/templates/homepage/navigate.html
{% load staticfiles %}

<head>
    <link rel="shortcut icon" type="image/gif" href="{% static 'homepage/images/bk.png' %}" />
    <title>{% block title %}Ebook{% endblock %}</title>
</head>

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Marcellus+SC" rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style_year.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'homepage/modal.css' %}" />


<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function(){
    $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(200);
    }, function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(200);
    });  
});
</script>

<script>
    jQuery(document).ready(function($) {
var $modal = $('#modal');

$('#launcher').on('click', openModal);

$modal
    //.on('click', closeModal)
    .on('click', '.modal-close', closeModal)
    .on('click', '.modal-dialog', function(event) {
    event.stopPropagation();  // prevent closing the modal window when user clicks on the window itself
});

function closeModal() {
    $modal.fadeOut();
};

function openModal() {
    $modal.fadeIn();
};
});
</script>   

<!--navigation_bar-->
<nav class="navbar navbar-default" id="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="{%url 'homepage:index' %}" style="color: white" >Ebook</a>
        </div>
        <!--links-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav" id="list">
                <li class="dropdown" id="cat">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: white">&nbsp;Category<span class="caret"></span></a>
                    <ul class="dropdown-menu" id="box">
                    <li><a href="{% url 'homepage:fy'%}" id="li">First Year</a></li>
                    <li><a href="{% url 'homepage:it'%}" id="li">Information technology</a></li>
                    <li><a href="{% url 'homepage:mech'%}" id="li">Mechanical</a></li>
                    <li><a href="{% url 'homepage:comp'%}" id="li">Computer technology</a></li>
                    <li><a href="{% url 'homepage:extc'%}" id="li">Electronics and Telecommunication</a></li>
                    <li><a href="{% url 'homepage:instru'%}" id="li">Instrumentation</a></li>
                    <li><a href="{% url 'homepage:civil'%}" id="li">Civil</a></li>
                    </ul>
                </li>
                <li class="" id="cat"><a href="{% url 'blog:blog-base'%}" style="color: white">&nbsp;Forum</a></li>
                <!--li class=""  id="cat"><a href="#" style="color: white">&nbsp;About us</a></li>
                <li class="" id="cat"><a href="#" style="color: white">&nbsp;Help</a></li-->
            </ul>

            <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'homepage:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" id="search" name="q" value="{{request.GET.q}}" placeholder="Search">
                        <button class="search_icon" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="" id="list">
                {% if user.is_authenticated %}
                <li><a href="{% url 'blog:post-create' %}" style="color:white">New Post</a></li>
                <li><a href="{% url 'profile' %}" style="color:white">Profile</a></li>
                <li><a href="{% url 'homepage:log_out' %}" style="color:white" >&nbsp; Logout</a></li>
                {% else %}
                <li><a href="{% url 'homepage:log_in' %}?next={{request.path}}" style="color:white" >&nbsp; Login</a></li>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
{% block body %}
{% endblock %}
</div>

<div id="modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <button type="button" class="modal-close" tabindex="-1">&times;</button>
        <h2>Just 1 more step!</h2><br/><p>To download the book you need to <a href="{% url 'homepage:log_in' %}?next={{request.path}}">login&nbsp;<img src="https://img.icons8.com/ultraviolet/40/000000/enter-2.png"></a></p>
    </div>
</div>

homepage/templates/homepage/profile.html
{% extends "homepage/navigate.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row" id="section">
    <div class="content-section" style="margin-left:5%">&nbsp; 
          <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit"><a href="{% url 'homepage:index' %}">Update</a></button>
          </div>
      </form>
    </div>
    </div>
{% endblock %}

homepage/templates/homepage/search.html
{% extends 'homepage/navigate.html' %}
{% block title %}Search{% endblock %}

{% block body %}
    <div class="row" id="section">
        <div class="container-fluid">&nbsp;
            <!--Search for year or branch-->
            {% if category %}
            <div>
                <p class="well" id="title">Subjects</p>
                </div>
                <div class="container-fluid">
                    {% for category in category %}
                        <div class="col-sm-12">
                        <hr/>
                        <p id="title1" style="font-size: 30px;">{{category.year}}<a href="{% url 'homepage:more' category.year%}" id="more">See more.....</a></p>
                        </div>
        
                        {% for subject in category.subject_set.all|slice:":4"%}
                            <div class="col-sm-3" > &nbsp;
                                    <a href="{% url 'homepage:seperate' subject.sub_title %}">
                                        <img src="{{ subject.sub_logo.url }}" class="img-responsive" id="blocks">
                                    </a>
                                    <div class="caption" id="pic">
                                        <p>{{ subject.sub_title }}</p>&nbsp;
                                    </div>
                            </div>
                        {% endfor %}
                    
                    {% endfor %}
                </div>
            <!--Search for Subject_title-->
            {% elif subject %}
                {% for subject in subject %}
                    <div class="col-sm-12">
                    <p id="title1" style="font-size: 50px;">{{subject.sub_title}}</p>
                    </div>
                    <div class="container-fluid">
                        {% for bk in subject.book_set.all %}
                        &nbsp;<img src="{{ bk.book_logo.url }}" class="img-responsive" id="sep_cover"/>
                        <div class="caption" id="pic">
                            <div >
                                <p id="sep_detail">{{ bk.book_title }}</p>&nbsp;
                                <p id="sep_detail">{{ bk.author }}</p>&nbsp;<p id="sep_detail">{{ bk.book_detail }}</p>
                                {% if user.is_authenticated %}
                                <a href="{{ bk.book.url }}" class="btn btn-info btn-lg" id="sep_download">
                                    <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                                {% else %}
                                <a href="#" class="btn btn-info btn-lg" style="margin-right: 5%;margin-top: -8%;float: right;" id="launcher">
                                        <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                                {% endif %}
                            </div>
                            &nbsp;
                            <hr/>
                        {% endfor %}
                {% endfor %}


            <!--Search for Bk_title or author-->
            {% elif book %}
                {% for bk in book%}
                    <div>
                        <p id="title">{{ bk.book_title }}</p>
                    </div>&nbsp;
                    <div class="container-fluid">
                        <img src="{{ bk.book_logo.url }}" class="img-responsive" id="bk_cover"></a>
                        <div class="caption" id="pic">
                            <div id="detail">
                                <p>{{ bk.author }}</p>&nbsp;<p>{{ bk.subject.sub_title }}</p>&nbsp;<p>{{ bk.book_detail }}</p>
                                        {% if user.is_authenticated %}
                                        <a href="{{ bk.book.url }}" class="btn btn-info btn-lg" id="download">
                                            <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                                        {% else %}
                                        <a href="{% url 'homepage:log_in' %}" class="btn btn-info btn-lg" id="download">
                                                <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                                        {% endif %}
                            </div>
                        </div>                   
                    </div>&nbsp;
                {% endfor %}
            </div>
        </div>

            {% else %}
            <div class="row" id="error_box">
                <div class="container-fluid">
                    <p id="error">Sorry....Couldn't find any match.</p>
                    <p id="error1">Try typing something else</p>
                </div>
            </div>
            {% endif %} 
{% endblock %}

homepage/templates/homepage/seperate.html
{% extends 'homepage/navigate.html' %}
{% block title %}{{subject.sub_title}}{% endblock %}

{% block body %}
    <div class="row" id="section">
        <div>
        <p id="title" class="well">{{subject.sub_title}}</p>
        </div>&nbsp;
        <div class="container-fluid">
                {% for bk in subject.book_set.all %}
                &nbsp;<img src="{{ bk.book_logo.url }}" class="img-responsive" id="sep_cover"/>
                <div class="caption" id="pic">
                    <div >
                        <p id="sep_detail">{{ bk.book_title }}</p>&nbsp;
                        <p id="sep_detail">{{ bk.author }}</p>&nbsp;<p id="sep_detail">{{ bk.book_detail }}</p>
                        {% if user.is_authenticated %}
                        <a href="{{ bk.book.url }}" class="btn btn-info btn-lg" id="sep_download">
                            <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                        {% else %}
                        <a href="#" class="btn btn-info btn-lg" style="margin-right: 5%;margin-top: -8%;float: right;" id="launcher">
                                <span class="glyphicon glyphicon-download-alt"></span> Download</a>
                        {% endif %}
                    </div>
                    &nbsp;
                    <hr/>
                {% endfor %}
        </div>
    </div>  


{% endblock %}

homepage/templates/homepage/signup.html
{% extends 'homepage/navigate.html' %}
{% block title %}Signup{% endblock %}

{% block body %}
<!--Signin-->
<form action="{% url 'homepage:signup' %}" method="POST">
    {% csrf_token %}
    <div id="login-box">
        <div class="left">
            <h1 id="h1">Sign up</h1>
                {% if error_message %}
                <p style="color:white"><strong>{{ error_message }}</strong></p>
                {% endif %}
                <input type="text" name="username" placeholder="Username" />
                <input type="text" name="email" placeholder="E-mail" />
                <input type="password" name="password" placeholder="Password" />            
                <input type="submit" name="signup_submit" value="Sign me up" />
        </div>
    </div>
</form>
{% endblock %}

homepage/templates/homepage/year.html
{% extends 'homepage/navigate.html' %}
{% block title %}Branch{% endblock %}

{% block body %}
    <div class="row" id="section">
        <div>
        <p class="well" id="title">Subjects</p>
        </div>
        <div class="container-fluid">
            {% for category in category %}
                <div class="col-sm-12">
                <hr/>
                <p id="title1" style="font-size: 30px;">{{category.year}}<a href="{% url 'homepage:more' category.year%}" id="more">See more.....</a></p>
                </div>

                {% for subject in category.subject_set.all|slice:":4"%}
                    <div class="col-sm-3" > &nbsp;
                            <a href="{% url 'homepage:seperate' subject.sub_title %}">
                                <img src="{{ subject.sub_logo.url }}" class="img-responsive" id="blocks">
                            </a>
                            <div class="caption" id="pic">
                                <p>{{ subject.sub_title }}</p>&nbsp;
                            </div>
                    </div>
                {% endfor %}
            
            {% endfor %}
        </div>
    </div>
{% endblock %}